// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuUxYH554SRQLpJ3uf8IhVvvNUHocGt5Q',
    appId: '1:333340038175:web:3071fa7cc5dc91f4bf712a',
    messagingSenderId: '333340038175',
    projectId: 'bookmates-agora',
    authDomain: 'bookmates-agora.firebaseapp.com',
    storageBucket: 'bookmates-agora.appspot.com',
    measurementId: 'G-9BD0YZVPRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD3OXiay3NKcCU9pHX0Ihz1U-bldIFX9o',
    appId: '1:333340038175:android:76079bf7aed8351ebf712a',
    messagingSenderId: '333340038175',
    projectId: 'bookmates-agora',
    storageBucket: 'bookmates-agora.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuBNPgvdhvDCwg-gNn6ghkfnJ_n9klV8s',
    appId: '1:333340038175:ios:ec1fba8352cefc4abf712a',
    messagingSenderId: '333340038175',
    projectId: 'bookmates-agora',
    storageBucket: 'bookmates-agora.appspot.com',
    iosBundleId: 'com.example.agoraDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuBNPgvdhvDCwg-gNn6ghkfnJ_n9klV8s',
    appId: '1:333340038175:ios:a4c5b12e51b61c31bf712a',
    messagingSenderId: '333340038175',
    projectId: 'bookmates-agora',
    storageBucket: 'bookmates-agora.appspot.com',
    iosBundleId: 'com.example.agoraDemo.RunnerTests',
  );
}
